----------------------------------------------------------------------------------------------------
--- Author: Long Thai
--- Modified: 2022-07-30
--- Description: File nµy dïng ®Ó ®¨ng ký task cho nh©n vËt
--- task bit id 1-31, value 0-1
--- task byte id 1-3, value 0-255
----------------------------------------------------------------------------------------------------
WTASKID_BEGIN = 4000; -- Task b¾t ®Çu sö dông
----------------------------------------------------------------------------------------------------

WTASKID_CURRENT_DATE = 4001; -- L­u ngµy yyyymmdd hiÖn t¹i cña server vµo nh©n vËt, dïng ®Ó check c¸c ho¹t ®éng theo ngµy
WTASKID_CURRENT_LANGUAGE = 4002; -- L­u ng«n ng÷ cña nh©n vËt

WTASKID_GMSTATE_BIT = 4003; -- L­u theo bit tr¹ng th¸i tÝnh n¨ng cña gm/admin/mod, hç trî ®c tèi ®a 31 tr¹ng th¸i
WTASKID_GMSTATE_BIT_GMBUFF = 1;
WTASKID_GMSTATE_BIT_UNUSE = 2;
WTASKID_GMSTATE_BIT_UNUSE = 3;
WTASKID_GMSTATE_BIT_UNUSE = 4;
WTASKID_GMSTATE_BIT_UNUSE = 5;
WTASKID_GMSTATE_BIT_UNUSE = 6;
WTASKID_GMSTATE_BIT_UNUSE = 7;

WTASKID_PLAYERSTATE_BIT = 4004; -- L­u theo bit tr¹ng th¸i tÝnh n¨ng cña player, hç trî ®c tèi ®a 31 tr¹ng th¸i
WTASKID_PLAYERSTATE_BIT_NEWBIE = 1;
WTASKID_PLAYERSTATE_BIT_CAMLOGIN = 2;
WTASKID_PLAYERSTATE_BIT_CAMCHAT = 3;
WTASKID_PLAYERSTATE_BIT_BATGIAM = 4;
WTASKID_PLAYERSTATE_BIT_BUFFTEST = 5;
WTASKID_PLAYERSTATE_BIT_GIVECODETEST = 6;
WTASKID_PLAYERSTATE_BIT_ACTIVETESTCARD = 7;
WTASKID_PLAYERSTATE_BIT_DISABLE_EFFECT = 8;
WTASKID_PLAYERSTATE_BIT_FINISHTASK_NEWBIE_GIVEDAILY2 = 9;

WTASKID_LAST_MAC_PART1 = 4005; -- L­u 1/3 n÷a ®Çu chuçi mac m· hãa cña nh©n vËt
WTASKID_LAST_MAC_PART2 = 4006; -- L­u 1/3 n÷a sau chuçi mac m· hãa cña nh©n vËt
WTASKID_LAST_MAC_PART3 = 4007; -- L­u 1/3 n÷a sau chuçi mac m· hãa cña nh©n vËt
WTASKID_CURRENT_MAC_PART1 = 4008; -- L­u 1/3 n÷a ®Çu chuçi mac m· hãa cña nh©n vËt
WTASKID_CURRENT_MAC_PART2 = 4009; -- L­u 1/3 n÷a sau chuçi mac m· hãa cña nh©n vËt
WTASKID_CURRENT_MAC_PART3 = 4010; -- L­u 1/3 n÷a sau chuçi mac m· hãa cña nh©n vËt

WTASKID_RUONG_BNL_DAILY_COUNT = 4011; -- L­u sè lÇn më r­¬ng B¸t Nh· Lín mçi ngµy sÏ reset
WTASKID_RUONG_LSB_DAILY_COUNT = 4012; -- L­u sè lÇn më r­¬ng B¸t Nh· Lín mçi ngµy sÏ reset
WTASKID_RUONG_DHC_DAILY_COUNT = 4013; -- L­u sè lÇn më r­¬ng B¸t Nh· Lín mçi ngµy sÏ reset
WTASKID_RUONG_KDYV_DAILY_COUNT = 4014; -- L­u sè lÇn më r­¬ng B¸t Nh· Lín mçi ngµy sÏ reset

WTASKID_NEWBATTLE_MERIT_POINT = 701; -- §iÓm c«ng tr¹ng chiÕn tr­êng
WTASKID_NEWBATTLE_EXPAWARD_DAILY_COUNT = 761; -- NhËn th­ëng 1 lÇn exp chiÕn tr­êng chÝnh h»ng ngµy
WTASKID_NEWBATTLE_LASTDATA_DATE = 4015; -- Ghi l¹i ngµy tham gia chiÕn tr­êng
WTASKID_NEWBATTLE_LASTDATA_BYTE = 4016; -- Ghi l¹i d÷ liÖu cña trËn cuèi, hç trî tèi ®a ®c 3 id
WTASKID_NEWBATTLE_LASTDATA_BYTE_JOINHOUR = 1; -- Ghi l¹i giê vµo chiÕn tr­êng
WTASKID_NEWBATTLE_LASTDATA_BYTE_JOINMIN = 2; -- Ghi l¹i phót vµo chiÕn tr­êng
WTASKID_NEWBATTLE_LASTDATA_BYTE_RANK = 3; -- Ghi l¹i h¹ng cña trËn cuèi, hç trî ®c gi¸ trÞ 0-255

WTASKID_PLAYERSTATE_CAMLOGIN_TOTALTIME = 4017;
WTASKID_PLAYERSTATE_CAMLOGIN_REMAINING = 4018;
WTASKID_PLAYERSTATE_CAMCHAT_TOTALTIME = 4019;
WTASKID_PLAYERSTATE_CAMCHAT_REMAINING = 4020;
WTASKID_PLAYERSTATE_BATGIAM_TOTALTIME = 4021;
WTASKID_PLAYERSTATE_BATGIAM_REMAINING = 4022;

WTASKID_NEWBIE_AWARD_GIVE_STATUS = 4023; -- Ghi l¹i tr¹ng th¸i nhËn quµ cÊp theo thø tù t¨ng dÇn

WTASKID_WEBSERVICE_BYTE = 4024; -- Ghi l¹i tr¹ng th¸i nhËp pass
WTASKID_WEBSERVICE_BYTE_VERIFY_FAILED_COUNT = 1; -- sè lÇn nhËp sai pass
WTASKID_WEBSERVICE_BYTE_UNUSE = 2;
WTASKID_WEBSERVICE_BYTE_UNUSE = 3;

WTASKID_DUATOPBXH_AWARD_GIVE_STATUS_BIT = 4025; -- L­u theo d¹ng bit c¸c phÇn th­ëng top ®· nhËn
WTASKID_DUATOPBXH_AWARD_GIVE_STATUS_BIT_MERIT = 1;
WTASKID_DUATOPBXH_AWARD_GIVE_STATUS_BIT_LEVEL = 2;
WTASKID_DUATOPBXH_AWARD_GIVE_STATUS_BIT_UNUSE = 3;
WTASKID_DUATOPBXH_AWARD_GIVE_STATUS_BIT_UNUSE = 4;
WTASKID_DUATOPBXH_AWARD_GIVE_STATUS_BIT_UNUSE = 5;
WTASKID_DUATOPBXH_AWARD_GIVE_STATUS_BIT_UNUSE = 6;
WTASKID_DUATOPBXH_AWARD_GIVE_STATUS_BIT_UNUSE = 7;

-- L­u c¸c vËt phÈm nhËn tõ thÎ t©n thñ
WTASKID_NEWBIE_BIT_GIVE_STATUS = 4026;
WTASKID_NEWBIE_BIT_GIVE_AMHUYET = 1;
WTASKID_NEWBIE_BIT_GIVE_THANHLONGTUONG = 2;
WTASKID_NEWBIE_BIT_GIVE_THANHLONGSOAI = 3;
WTASKID_NEWBIE_BIT_GIVE_VOSONGCHIENTHAN = 4;
WTASKID_NEWBIE_BIT_GIVE_VANSUC3 = 5;
WTASKID_NEWBIE_BIT_GIVE_KIMXA6 = 6;
WTASKID_NEWBIE_BIT_GIVE_KIMXA3 = 7;
WTASKID_NEWBIE_BIT_GIVE_SM3 = 8;
WTASKID_NEWBIE_BIT_GIVE_SM4 = 9;
WTASKID_NEWBIE_BIT_GIVE_SM5 = 10;
WTASKID_NEWBIE_BIT_GIVE_THUONGHAIDICHAU = 11;
WTASKID_NEWBIE_BIT_GIVE_BOTTRANCHAU = 12;
WTASKID_NEWBIE_BIT_GIVE_CHUYENSINH = 13;
WTASKID_NEWBIE_BIT_GIVE_HOACANH_90 = 14;
WTASKID_NEWBIE_BIT_GIVE_MATTICHBIDIEN = 15;
WTASKID_NEWBIE_BIT_GIVE_MATTICHTHUONG = 16;
WTASKID_NEWBIE_BIT_GIVE_DIEMLUYENMATTICH = 17;
WTASKID_NEWBIE_BIT_GIVE_KINHMACHVOTHANH = 18;
WTASKID_NEWBIE_BIT_GIVE_KINHMACHDONGNHAN = 19;
WTASKID_NEWBIE_BIT_GIVE_KINHMACHNGANNHAN = 20;
WTASKID_NEWBIE_BIT_GIVE_CHANKHI = 21;
WTASKID_NEWBIE_BIT_GIVE_TINVAT = 22;
WTASKID_NEWBIE_BIT_GIVE_HIEUBANG = 23;
WTASKID_NEWBIE_BIT_GIVE_VANG = 24;
WTASKID_NEWBIE_BIT_GIVE_DANHHIEU = 25;
WTASKID_NEWBIE_BIT_GIVE_DUOCPHAM = 26;
WTASKID_NEWBIE_BIT_GIVE_SUADO = 27;
WTASKID_NEWBIE_BIT_GIVE_MAIDAMAGE = 28;
WTASKID_NEWBIE_BIT_GIVE_DAQUY = 29;
WTASKID_NEWBIE_BIT_GIVE_NGOAITRANG = 30;
WTASKID_NEWBIE_BIT_GIVE_THUCUOI = 31;
--WTASKID_NEWBIE_BIT_GIVE_CHUTUOCTUONG = 32;

WTASKID_NEWBIE_BIT_GIVE2_STATUS = 4027; -- L­u c¸c vËt phÈm nhËn tõ thÎ t©n thñ, v× nhiÒu qu¸ nªn thªm task
WTASKID_NEWBIE_BIT_GIVE2_PHUCSINHPET1 = 1;
WTASKID_NEWBIE_BIT_GIVE2_PHUCSINHPET2 = 2;
WTASKID_NEWBIE_BIT_GIVE2_HACBACHKY = 3;
WTASKID_NEWBIE_BIT_GIVE2_SACHPET5 = 4;
WTASKID_NEWBIE_BIT_GIVE2_SPECROUTE = 5;
WTASKID_NEWBIE_BIT_GIVE2_SETBUFF = 6;
WTASKID_NEWBIE_BIT_GIVE2_CHIENCUONG = 7;
--WTASKID_NEWBIE_BIT_GIVE2_TAYTAMLUYENLO = 8;
WTASKID_NEWBIE_BIT_GIVE_THUONGHAIDICHAU6 = 8;
WTASKID_NEWBIE_BIT_GIVE2_DIEUDUONG = 9;
WTASKID_NEWBIE_BIT_GIVE2_YEUQUYET = 10;
WTASKID_NEWBIE_BIT_GIVE2_THANHANH = 11;
WTASKID_NEWBIE_BIT_GIVE2_COKIMTHACH = 12;
WTASKID_NEWBIE_BIT_GIVE2_TUCHAN = 13;
WTASKID_NEWBIE_BIT_GIVE2_LUUKIM = 14;
WTASKID_NEWBIE_BIT_GIVE2_THIENVANTHACH = 15;
WTASKID_NEWBIE_BIT_GIVE2_TTTT = 16;
WTASKID_NEWBIE_BIT_GIVE2_DAIDINHHON = 17;
WTASKID_NEWBIE_BIT_GIVE2_NLKIMXA = 18;
WTASKID_NEWBIE_BIT_GIVE2_HOACANH_150 = 19;
WTASKID_NEWBIE_BIT_GIVE2_BOTTRANCHAU = 20;
WTASKID_NEWBIE_BIT_GIVE2_KIMXA7 = 21;
WTASKID_NEWBIE_BIT_GIVE2_DANHHIEU = 22;
WTASKID_NEWBIE_BIT_GIVE2_TAYTAMLUYENLO3 = 24;
WTASKID_NEWBIE_BIT_GIVE2_KIMXA8 = 25;

WTASKID_PLANT_GIVEWATER_LAST_POS = 4028; -- l­u vÞ trÝ t­íi n­íc cuèi cïng

WTASKID_CODETEST_BYTE_TASK = 4029; -- l­u nhiÖm vô alphatest
WTASKID_CODETEST_BYTE_TASK_BATNHALON = 1;
WTASKID_CODETEST_BYTE_TASK_VANTIEU = 2;
WTASKID_CODETEST_BYTE_TASK_TAINGUYENCHIEN = 3;

WTASKID_CODETEST_BIT_GIVE_STATUS = 4030; -- l­u tr¹ng th¸i nhËn giftcode nhiÖm vô 1-31 mèc
WTASKID_CODETEST_BIT_GIVE_MOC1 = 1;
WTASKID_CODETEST_BIT_GIVE_MOC2 = 2;
WTASKID_CODETEST_BIT_GIVE_MOC3 = 3;
WTASKID_CODETEST_BIT_GIVE_MOC4 = 4;

WTASKID_RUONG_HOATDONG_DAILY_COUNT = 4031; -- L­u sè lÇn më r­¬ng ho¹t ®éng mçi ngµy sÏ reset

WTASKID_DUATOP_AWARD_GIVE_RHD_STATUS_BIT = 4032; -- L­u theo d¹ng bit c¸c phÇn th­ëng top ®· nhËn
WTASKID_DUATOP_AWARD_GIVE_RHD_STATUS_BIT_TOP_YESTERDAY = 1;

WTASKID_TANGKIEM_BYTE = 4033 -- Task fix ®óp phÇn th­ëng tµng kiÕm;
WTASKID_TANGKIEM_BYTE_GIVE_STAGE_AWARD_STATUS = 1;

-- Task nhiÖm vô nhËn ®å h»ng nµy
WTASKID_DAILYTASK_BYTE = 4034; 
WTASKID_DAILYTASK_BYTE_CTC_DONE = 1; -- Sè lÇn tham gia chiÕn tr­êng chÝnh
WTASKID_DAILYTASK_BYTE_CTP_DONE = 2; -- Sè lÇn tham gia chiÕn tr­êng phô
WTASKID_DAILYTASK_BYTE_TNC_DONE = 3; -- Sè lÇn hoµn thµnh tµi nguyªn chiÕn

-- Task nhËn hç trî 1 lÇn mçi ngµy
WTASKID_NEWBIE_GIVEDAILY_BIT = 4035;
WTASKID_NEWBIE_GIVEDAILY_BIT_VANG = 1;
WTASKID_NEWBIE_GIVEDAILY_BIT_BIDIEN = 2;
WTASKID_NEWBIE_GIVEDAILY_BIT_TUCHAN = 3;
WTASKID_NEWBIE_GIVEDAILY_BIT_LICHLUYEN = 4;
WTASKID_NEWBIE_GIVEDAILY_BIT_MANHMACGIA = 5;
WTASKID_NEWBIE_GIVEDAILY_BIT_SACHKYNANGPET = 6;
WTASKID_NEWBIE_GIVEDAILY_BIT_THUONGHAIDICHAU = 7;
WTASKID_NEWBIE_GIVEDAILY_BIT_BOTTRANCHAU = 8;
WTASKID_NEWBIE_GIVEDAILY_BIT_DAMAI = 9;
WTASKID_NEWBIE_GIVEDAILY_BIT_TTTT= 10;
WTASKID_NEWBIE_GIVEDAILY_BIT_TAYTAMLUYENLO = 11;
WTASKID_NEWBIE_GIVEDAILY_BIT_LUUKIM = 12;
WTASKID_NEWBIE_GIVEDAILY_BIT_THIENVANTHACH = 13;
WTASKID_NEWBIE_GIVEDAILY_BIT_COKIMTHACH = 14;
WTASKID_NEWBIE_GIVEDAILY_BIT_DAQUY = 15;
WTASKID_NEWBIE_GIVEDAILY_BIT_VANSUC3 = 16;
WTASKID_NEWBIE_GIVEDAILY_BIT_TAYTAMLUYENLO5 = 17;
WTASKID_NEWBIE_GIVEDAILY_BIT_TCL = 18;
WTASKID_NEWBIE_GIVEDAILY_BIT_TMKL = 19;
WTASKID_NEWBIE_GIVEDAILY_BIT_TAYTAMLUYENLO7 = 20;
WTASKID_NEWBIE_GIVEDAILY_BIT_SACHKYNANGPET6 = 21;
WTASKID_NEWBIE_GIVEDAILY_BIT_NLHOACANH = 22;
WTASKID_NEWBIE_GIVEDAILY_BIT_HUYETBODE = 23;

--Task nhËn th­ëng mèc ®iÓm c«ng tr¹ng
WTASKID_MERITPOINT_AWARD_BIT = 4036;
WTASKID_MERITPOINT_AWARD_BIT_100K = 1;
WTASKID_MERITPOINT_AWARD_BIT_200K = 2;
WTASKID_MERITPOINT_AWARD_BIT_300K = 3;
WTASKID_MERITPOINT_AWARD_BIT_500K = 4;
WTASKID_MERITPOINT_AWARD_BIT_1000K = 5;
WTASKID_MERITPOINT_AWARD_BIT_2000K = 6;
WTASKID_MERITPOINT_AWARD_BIT_3000K = 7;
WTASKID_MERITPOINT_AWARD_BIT_4000K_OLD = 8;
WTASKID_MERITPOINT_AWARD_BIT_5000K_OLD = 9;
WTASKID_MERITPOINT_AWARD_BIT_6000K = 10;
WTASKID_MERITPOINT_AWARD_BIT_8000K = 11;
WTASKID_MERITPOINT_AWARD_BIT_10000K = 12;
WTASKID_MERITPOINT_AWARD_BIT_5000K = 13;
WTASKID_MERITPOINT_AWARD_BIT_4000K=14;

--Task nhiÖm vô ®Æc thï lµm 1 lÇn
WTASKID_NEWBIE_GIVEDAILY2_BIT = 4037;
WTASKID_NEWBIE_GIVEDAILY2_BIT_VANG = 1;
WTASKID_NEWBIE_GIVEDAILY2_BIT_BIDIEN = 2;
WTASKID_NEWBIE_GIVEDAILY2_BIT_TUCHAN = 3;
WTASKID_NEWBIE_GIVEDAILY2_BIT_LICHLUYEN = 4;
WTASKID_NEWBIE_GIVEDAILY2_BIT_MANHMACGIA = 5;
WTASKID_NEWBIE_GIVEDAILY2_BIT_SACHKYNANGPET = 6;
WTASKID_NEWBIE_GIVEDAILY2_BIT_THUONGHAIDICHAU = 7;
WTASKID_NEWBIE_GIVEDAILY2_BIT_BOTTRANCHAU = 8;
WTASKID_NEWBIE_GIVEDAILY2_BIT_DAMAI = 9;
WTASKID_NEWBIE_GIVEDAILY2_BIT_TTTT= 10;
WTASKID_NEWBIE_GIVEDAILY2_BIT_TAYTAMLUYENLO = 11;
WTASKID_NEWBIE_GIVEDAILY2_BIT_LUUKIM = 12;
WTASKID_NEWBIE_GIVEDAILY2_BIT_THIENVANTHACH = 13;
WTASKID_NEWBIE_GIVEDAILY2_BIT_COKIMTHACH = 14;
WTASKID_NEWBIE_GIVEDAILY2_BIT_DAQUY = 15;
WTASKID_NEWBIE_GIVEDAILY2_BIT_VANSUC3 = 16;
WTASKID_NEWBIE_GIVEDAILY2_BIT_TAYTAMLUYENLO7 = 17;

-- Task ghi l¹i sè lÇn sö dông NSMM
-- do bÞ bug sö dông v­ît qu¸ sè lÇn nªn ph¸t sinh thªm 2 task míi kÕt hîp check víi task cò
WTASKID_USE_NUOA_DAILY = 4038;
WTASKID_USE_NGOISAO_DAILY = 4039;

-- Task nhiÖm vô hµng tuÇn
WTASKID_CURRENT_WEEK = 4040;
WTASKID_WEEKLYTASK_BYTE = 4041;
WTASKID_WEEKLYTASK_BYTE_CTC_DONE = 1;
WTASKID_WEEKLYTASK_BYTE_CTP_DONE = 2;
WTASKID_WEEKLYTASK_BYTE_TNC_DONE = 3;
WTASKID_WEEKLYTASK2_BYTE = 4042;
WTASKID_WEEKLYTASK2_BYTE_BNL_DONE = 1;
WTASKID_WEEKLYTASK2_BYTE_VANTIEU_DONE = 2;
WTASKID_WEEKLYTASK2_BYTE_CUOPTIEU_DONE = 3;
WTASKID_WEEKLYTASK2_BYTE_BNN_DONE = 4;
WTASKID_WEEKLYTASK2_BYTE_HATGIONG_DONE = 5;

-- Task tr¹ng th¸i nhËn th­ëng mçi tuÇn
WTASKID_WEEKLYTASK_GIVE_BIT = 4043;
WTASKID_WEEKLYTASK_GIVE_BIT_DANHHIEU = 1;
WTASKID_WEEKLYTASK_GIVE_BIT_MANHBIDIEN = 2;
WTASKID_WEEKLYTASK_GIVE_BIT_DICHAU = 3;
WTASKID_WEEKLYTASK_GIVE_BIT_TAYTAMLUYENLO = 4;
WTASKID_WEEKLYTASK_GIVE_BIT_TCL = 5;
WTASKID_WEEKLYTASK_GIVE_BIT_TMKL = 6;
WTASKID_WEEKLYTASK_GIVE_BIT_TAYTAMLUYENLO7 = 7;
WTASKID_WEEKLYTASK_GIVE_BIT_Vang = 8;
WTASKID_WEEKLYTASK_GIVE_BIT_THANHLONGHON = 9;

-- Task nhiÖm vô t©n thñ 1
WTASKID_SUPPORT1_TASK_BYTE = 4044;
WTASKID_SUPPORT1_TASK_BYTE_CTC_DONE = 1;
WTASKID_SUPPORT1_TASK_BYTE_CTP_DONE = 2;
WTASKID_SUPPORT1_TASK_BYTE_TNC_DONE = 3;
WTASKID_SUPPORT1_TASK2_BYTE = 4045;
WTASKID_SUPPORT1_TASK2_BYTE_BNL_DONE = 1;
WTASKID_SUPPORT1_TASK2_BYTE_VANTIEU_DONE = 2;
WTASKID_SUPPORT1_TASK2_BYTE_CUOPTIEU_DONE = 3;
WTASKID_SUPPORT1_TASK2_BYTE_BNN_DONE = 4;

-- Task tr¹ng th¸i nhËn th­ëng nhiÖm vô hç trî t©n thñ
WTASKID_SUPPORT1_GIVE_BIT = 4046;
WTASKID_SUPPORT1_GIVE_BIT_BUACUONGHOA = 1;
WTASKID_SUPPORT1_GIVE_BIT_MANHBIDIEN27 = 2;
WTASKID_SUPPORT1_GIVE_BIT_MANHBIDIEN30 = 3;
WTASKID_SUPPORT1_GIVE_BIT_DICHAU = 4;
WTASKID_SUPPORT1_GIVE_BIT_THIENTHACHTINHTHACH = 5;
WTASKID_SUPPORT1_GIVE_BIT_DAIDINHHON = 6;
WTASKID_SUPPORT1_GIVE_BIT_CHANVOHONTHACH = 7;

-- Task më r­¬ng
WTASKID_RUONG_QUY_MAO_OPEN_COUNT = 4047;

-- Task giíi h¹n më r­¬ng b»ng h×nh thøc cô thÓ cã d¹ng AAAABBBB, AAAA lµ giíi h¹n më b»ng xu, BBBB lµ giíi h¹n më b»ng vµng
WTASKID_BACHBAORUONG_OPENTYPE_LIMIT = 4048;

-- Task treo m¸y online nhËn th­ëng
WTASKID_TREO_ONLINE_MIN_DAILY_COUNT = 4049;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT = 4050;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY1_10M = 1;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY1_20M = 2;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY1_1H = 3;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY1_2H = 4;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY2_10M = 5;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY2_20M = 6;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY2_1H = 7;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY2_2H = 8;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY3_10M = 9;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY3_20M = 10;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY3_1H = 11;
WTASKID_TREO_ONLINE_NHAN_THUONG_BIT_DAY3_2H = 12;

-- Task më r­¬ng boss TNC
WTASKID_OPENBOX_BOSSTNC_LASTTIME = 4051;
WTASKID_OPENBOX_BOSSTNC_TODAY = 4052;

-- Task ghi l¹i tr¹ng th¸i nhËn th­ëng mèc ho¹t ®éng Th¸nh Ho¶ §µn
WTASKID_THANHHOADAN_ACCUMULATE_BIT_GIVE= 4053;
WTASKID_THANHHOADAN_ACTIVE_FIRE_COUNT = 4054;

WTASKID_LEVEL_AWARD_BIT = 4055
WTASKID_LEVEL_AWARD_BIT_LV73 = 1;
WTASKID_LEVEL_AWARD_BIT_LV799 = 2;
WTASKID_LEVEL_AWARD_BIT_LV1095= 3;
WTASKID_LEVEL_AWARD_BIT_LV1096= 4;
WTASKID_LEVEL_AWARD_BIT_LV1097= 5;
WTASKID_LEVEL_AWARD_BIT_LV1098= 6;
WTASKID_LEVEL_AWARD_BIT_LV1099= 7;
WTASKID_LEVEL_AWARD_BIT_LV1094= 8;
WTASKID_LEVEL_AWARD_BIT_LV1093= 9;
WTASKID_LEVEL_AWARD_BIT_LV1092= 10;

WTASKID_RUONG_BNN_DAILY_COUNT = 4056; -- L­u sè lÇn më r­¬ng B¸t Nh· Nhá mçi ngµy sÏ reset
---Task giíi h¹n gãi Thanh v©n ®¹i phó
WTASKID_THANHVANDAIPHU_LIMIT =4057;
----Task Th­ëng n¨ng ®éng N¨ng ®éng
WMISSION_AWARD_NANGDONG=4058;
WMISSION_AWARD_BIT_DAILY_NANGDONG_BATNHA =1;
WMISSION_AWARD_BIT_DAILY_NANGDONG_VANTIEU =2;
WMISSION_AWARD_BIT_DAILY_NANGDONG_CHIENTRUONGPHU =3;
WMISSION_AWARD_BIT_DAILY_NANGDONGCHIENTRUONGCHINH =4;
WMISSION_AWARD_BIT_NANGDONG_GIANHAPPHAI=5;
WMISSION_AWARD_BIT_NANGDONG_GIANHAPBANG=6;
WMISSION_AWARD_BIT_NANGDONG_GIANHAPPHEPHAI=7;
WMISSION_AWARD_BIT_NANGDONG_500_THIENKIEULENH=11;
WMISSION_AWARD_BIT_NANGDONG_1000_THIENKIEULENH=12;
WMISSION_AWARD_BIT_NANGDONG_1500_THIENKIEULENH=13;
WMISSION_AWARD_BIT_NANGDONG_2000_THIENKIEULENH=14;
--TASKID_LUCKYBOX_AWARD=4059 --- §· define ë lib/define
--TASKID_LUCKYBOX_COUNT=4060 -- §· define ë lib/define- TiÕp tôc th× nèi tiÕp =4061
WMISSION_AWARD_NANGDONG_CHECK=4061;
WMISSION_AWARD_NANGDONG_TKL_CHECK=4062;
WMISSION_TASK_BOSS_DHC_CHECK=4063;
WTASKID_AWARD_TASK_TOPSERVER_STATUS=4064;
WTASKID_AWARD_TASK_TOPHOACANH_STATUS=4065;
WTASKID_AWARD_TASK_GIANGSINHFEE_STATUS=4066;
WTASKID_TASK_HOAMACHVIPT12_STATUS=4067;
WTASKID_HOTROHANGTHANG2024_OLD =4068;
WTASKID_QHTUONG_UNLIMIT2024_TONG=4069;
WTASKID_QHTUONG_UNLIMIT2024_LIEU=4070;
WTASKID_MAMNGUQUA2024=4071;
WTASKID_TIENXUMAYMAN2024=4072;
WTASKID_CHUCPHUCMAYMAN2024=4073;
TASKID_HOTRO_NEW_2024_STATUS=4074;
TASKID_SAVE_CONGTRANG_DUATOP_2024=4075;
TASKID_SAVE_CONGTRANG_DUATOP_2024_STATUS=4076;
TASKID_BIT_CHECK_RESET_DUATOP_2024_STATUS=11;
TASKID_BIT_CHECK_RECOVER_DUATOP_2024_STATUS=12;
WTASKID_BAO_LUU_CT_DATE = 4077; -- using yp
WTASKID_BAO_LUU_CT_RANK = 4078; -- using yp
WTASKID_BAO_LUU_CT_POINT = 4079; -- using yp
WTASKID_OPENBOX_BOSSTET2024_LASTTIME=4080;
WTASKID_OPENBOX_BOSSTET2024_TODAY=4081;
WTASKID_GIVEBACK_HONOR=4082;
WTASKID_RUONG_TANGKIEM_DAILY_COUNT=4083;
WTASKID_RUONG_THAIHU_DAILY_COUNT=4084;
WTASKID_DAYLY_THAIHU_DAILY_COUNT=4085;
WTASKID_DAYLY_TANGKIEM_DAILY_COUNT=4086;
WTASKID_DAYLY_VANTIEU_DAILY_COUNT=4087;
WTASKID_DAYLY_BATNHALON_DAILY_COUNT=4088;
WTASKID_NHAN_THUONG_HOAMACHCANH=4090;
WTASKID_NHAN_THUONG_BIT_165HMC = 1;
WTASKID_NHAN_THUONG_BIT_170HMC = 2;
WTASKID_NHAN_THUONG_BIT_175HMC = 3;
WTASKID_NHAN_THUONG_BIT_180HMC = 4;
WTASKID_NHAN_THUONG_BIT_190HMC = 5;
WTASKID_NHAN_THUONG_BIT_200HMC = 6;

WTASKID_NHAN_THUONG_BIAVIAHE=4091;
WTASKID_NHAN_THUONG_BIADAHU=4092;
WTASKID_DAYLY_TNC_DAILY_COUNT=4093; ---task new chua su dung
WTASKID_HOTROHANGTHANG2024 =4094;
WTASKID_DAYLY_CAYTULINH =4095;
