----------------------------------------------------------------------------------------------------
--- Author: Long Thai
--- Modified: 2021-05-16
--- Description: File nµy dïng ®Ó ®¨ng ký task cho nh©n vËt
--- C¸c task cã thÓ dïng ®­îc:
--- Vng hiÖn ®ang sö dông task tõ 256, 272, max lµ 511
--- Nªn sö dông trong kho¶ng 400-511
----------------------------------------------------------------------------------------------------
WARLORD_TMPTASK_BEGIN = 400;
----------------------------------------------------------------------------------------------------

-- Start perfect dodge system
WARLORD_TMPTASK_OBS_POINT_GS = WARLORD_TMPTASK_BEGIN + 1;
WARLORD_TMPTASK_PERFDODGE_ADD_SCRIPT = WARLORD_TMPTASK_BEGIN + 2;

WARLORD_TMPTASK_CUR_STAMINA_GS = WARLORD_TMPTASK_BEGIN + 3;
WARLORD_TMPTASK_MAX_STAMINA_GS = WARLORD_TMPTASK_BEGIN + 4;

WARLORD_TMPTASK_DEX_POINT_GS = WARLORD_TMPTASK_BEGIN + 5;
WARLORD_TMPTASK_DODGEPOINT_ADD_SCRIPT = WARLORD_TMPTASK_BEGIN + 6;

WARLORD_TMPTASK_RIDE_HITPOINT_SCRIPT = WARLORD_TMPTASK_BEGIN + 7;
WARLORD_TMPTASK_RIDE_ARMORPOINT_SCRIPT = WARLORD_TMPTASK_BEGIN + 8;

WARLORD_TMPTASK_MAGIC_PARMOR_BUFF = WARLORD_TMPTASK_BEGIN + 9;
WARLORD_TMPTASK_PHYSICAL_PARMOR_BUFF = WARLORD_TMPTASK_BEGIN + 10;
-- End perfect dodge system

WARLORD_TMPTASK_JAILPLAYER_TIMETICK = WARLORD_TMPTASK_BEGIN + 11;

WARLORD_TMPTASK_ON_BUFF_READSPEED = WARLORD_TMPTASK_BEGIN + 12;
WARLORD_TMPTASK_LAST_READSPEED_X2 = WARLORD_TMPTASK_BEGIN + 13;
WARLORD_TMPTASK_LAST_READSPEED_X4 = WARLORD_TMPTASK_BEGIN + 14;

WARLORD_TMPTASK_DEATHTIME = WARLORD_TMPTASK_BEGIN + 15;

-- Start Héi hoa ®¨ng
WARLORD_TMPTASK_DENLONG_CURRENT = WARLORD_TMPTASK_BEGIN + 16;
WARLORD_TMPTASK_DENLONG_DURATION = WARLORD_TMPTASK_BEGIN + 17;
-- End Héi hoa ®¨ng

-- Start Captcha
WTASKTEMP_TEMP_CAPTCHA = WARLORD_TMPTASK_BEGIN + 18;
WTASKTEMP_CAPTCHA_FAILED_COUNT = WARLORD_TMPTASK_BEGIN + 19;
WTASKTEMP_CAPTCHA_FAILED_DURATION = WARLORD_TMPTASK_BEGIN + 20;
-- End Captcha

-- Start OTT
WARLORD_TMPTASK_OTT_PAY_TYPE = WARLORD_TMPTASK_BEGIN + 21;
WARLORD_TMPTASK_OTT_PAY_VALUE = WARLORD_TMPTASK_BEGIN + 22;
WARLORD_TMPTASK_OTT_ON_GAME = WARLORD_TMPTASK_BEGIN + 23;
WARLORD_TMPTASK_OTT_STATUS = WARLORD_TMPTASK_BEGIN + 24;
WARLORD_TMPTASK_OTT_TURN_SELECT = WARLORD_TMPTASK_BEGIN + 25;
WARLORD_TMPTASK_OTT_TURN_CHECK = WARLORD_TMPTASK_BEGIN + 26;
WARLORD_TMPTASK_OTT_PLAYER_ID1 = WARLORD_TMPTASK_BEGIN + 27;
WARLORD_TMPTASK_OTT_PLAYER_ID2 = WARLORD_TMPTASK_BEGIN + 28;
WARLORD_TMPTASK_OTT_MATCH_TOKEN_PART1 = WARLORD_TMPTASK_BEGIN + 29;
WARLORD_TMPTASK_OTT_MATCH_TOKEN_PART2 = WARLORD_TMPTASK_BEGIN + 30;
WARLORD_TMPTASK_OTT_START_TIME = WARLORD_TMPTASK_BEGIN + 31;
WARLORD_TMPTASK_OTT_WIN_BY_CHEAT = WARLORD_TMPTASK_BEGIN + 32;
-- End OTT

MASONMY_TMPTASK_HOI_PHU = WARLORD_TMPTASK_BEGIN + 33;

-- Ng¨n viÖc ®µo s©m nu«i rång 2 lÇn kÒ nhau, lÇn thø nhÊt ch­a ®µo xong mµ ®µo tiÕp lÇn 2 => mÊt l­ît
--MASONMY_TMPTASK_PLANT_DIG = WARLORD_TMPTASK_BEGIN + 34;
--MASONMY_TMPTASK_DRAGON_FEED = WARLORD_TMPTASK_BEGIN + 35;

WARLORD_TMPTASK_SYNC_MIN = WARLORD_TMPTASK_BEGIN + 36; -- L­u l¹i tæng sè lÇn ch¹y trigger 60s, sÏ bÞ reset nÕu chuyÓn gs
WARLORD_TMPTASK_SMS_SERVICE_IGNORE = WARLORD_TMPTASK_BEGIN + 37; -- Tr¹ng th¸i cña viÖc nhËp m· Otp hç trî

WARLORD_TMPTASK_TONGRESOURCES_NEW_LEVEL = WARLORD_TMPTASK_BEGIN + 38; -- L­u cÊp t¹m thêi cÇn set Tµi Nguyªn Bang Héi trong hµm callback
WARLORD_TMPTASK_TONGRESOURCES_DEDICATION_POINT = WARLORD_TMPTASK_BEGIN + 39; -- L­u sè ®iÓm ®ãng gãp cña Tµi Nguyªn Bang Héi trong hµm callback
WARLORD_TMPTASK_TONGRESOURCES_PLAYERTITLE_D = WARLORD_TMPTASK_BEGIN + 40; -- L­u t¹m thêi gi¸ trÞ nDetail lµ nLevel cña playertitle Tµi Nguyªn Bang Héi phôc vô c¸c hµm callback
WARLORD_TMPTASK_TONGRESOURCES_PLAYERTITLE_SELECTED = WARLORD_TMPTASK_BEGIN + 41; -- L­u t¹m thêi gi¸ trÞ nDanhHieuIdx cña item title Tµi Nguyªn Bang Héi phôc vô c¸c hµm callback

-- L­u thêi gian ®øng yªn t¹i chç trong chiÕn tr­êng, task nµy sÏ ®Õm dùa vµo hµm BT_KickSleeper
WARLORD_TMPTASK_NEWBATTLE_STAND_TIME = WARLORD_TMPTASK_BEGIN + 42;

--- D­íi nµy lµ dµnh cho 2022
-- L­u id trang bÞ ®Æt vµo PutinItem trong script n©ng cÊp ®å, sÏ ®­îc dïng trong hµm callback
WTASKTEMP_ITEMUPGRADE_TYPE_IDX = WARLORD_TMPTASK_BEGIN + 43;
WTASKTEMP_ITEMUPGRADE_PUTITEM1_IDX = WARLORD_TMPTASK_BEGIN + 44;
WTASKTEMP_ITEMUPGRADE_PUTITEM1_NUM = WARLORD_TMPTASK_BEGIN + 45;

-- L­u nhí c¸ch më r­¬ng
WTASKTEMP_RUONG_BNL_OPENTYPE = WARLORD_TMPTASK_BEGIN + 46; -- R­¬ng B¸t Nh· Lín
WTASKTEMP_RUONG_LSB_OPENTYPE = WARLORD_TMPTASK_BEGIN + 47; -- R­¬ng §Þa HuyÒn Cung
WTASKTEMP_RUONG_DHC_OPENTYPE = WARLORD_TMPTASK_BEGIN + 48; -- R­¬ng §Þa HuyÒn Cung
WTASKTEMP_RUONG_KDYV_OPENTYPE = WARLORD_TMPTASK_BEGIN + 49; -- R­¬ng KiÕm §·ng Yªn V©n

WTASKTEMPID_CLICKNPC_TIMEOUT = WARLORD_TMPTASK_BEGIN + 50; -- TÝnh thêi gian click npc

WTASKTEMPID_WEBSERVICE_IGNORE = WARLORD_TMPTASK_BEGIN + 51; -- Bá qua th«ng b¸o nhËp code cho ®Õn khi ®¨ng nhËp l¹i

----------------------------------------------------------------------------------------------------
WARLORD_TMPTASK_END = 511;
