RENAME_SWITCH = 1

RENAME_SPECIAL_FLAG_USE_RENAMECARD = 4096

RENAME_TYPE_PLAYER = 1
RENAME_TYPE_TONG = 2

RENAME_MIN_LENGTH = 8
RENAME_MAX_LENGTH = 32

_g_tbTypeNames = {
    [RENAME_TYPE_PLAYER] = "Nh©n vËt",
    [RENAME_TYPE_TONG] = "Bang héi",
}

_g_tbSwitches = {
    [RENAME_TYPE_PLAYER] = 1,
    [RENAME_TYPE_TONG] = 0,
}