WItemUpgrade:RegType({
    nGroupId = 10,
    szLogTitle = "upgrade_hoaphungtuong_thanhlongtuong_trangsuc1_100",
    szFeatureName = "N©ng cÊp HPT LÖnh Bµi thµnh Thanh Long T­íng Qu©n LÖnh Bµi 100%", nDateOpen = 1, nDateClose = 1, -- ngµy më tÝnh n¨ng, 1= lu«n më; 0= lu«n ®ãng; ®Þnh d¹ng yyyymmdd tøc lµ ®Þnh ngµy s½n
    szPutinTitle = "§Æt vµo HPT LÖnh Bµi",
    nPutinNum = 1,
    szConsumeInfo = " vµ <color=white>1 Háa Phông T­íng Qu©n LÖnh Bµi<color>",
    tbMaterialConsume = {
        nBattlePoint = 50000,
        tbItems = {
            { szName = "Thiªn Cang LÖnh", tbProp = { 2, 95, 204 }, nCount = 9 },
            { szName = "Thiªn M«n Kim LÖnh", tbProp = { 2, 1, 30370 }, nCount = 9 },
            { szName = "M¶nh Chu T­íc", tbProp = { 2, 1, 40016 }, nCount = 23 },
            { szName = "Hoµng Kim §¹i Hång Bao", tbProp = { 2, 1, 539 }, nCount = 15 },
        },
    },
    nMatchBodyMode = 3, -- ChÕ ®é tù ®éng tr¶ vÒ vËt phÈm phï hîp víi kiÓu h×nh ng­êi n©ng cÊp, 1= gi÷ nguyªn, 2= auto
    nEnhanceReq = 0, -- Yªu cÇu ®é c­êng hãa tõ mÊy? gi¸ trÞ =0 lµ ko kiÓm tra
    nEnhanceMode = 1, -- ChÕ ®é gi÷ c­êng hãa: gi¸ trÞ =1 lµ gi÷ nguyªn ®é c­êng hãa; =2 lµ trõ ®i 1 ®¬n vÞ; =3 lµ nÕu >= 7 th× vÒ l¹i 7, nÕu < 7 th× vÒ 0; 4= lµ vÒ 0
    nMaxRandom = 10000, -- Random tõ 1 -> m_nMaxRandom
    nLuckyNum = 10000, -- Trong kho¶ng tõ 1 -> m_nLuckyNum sÏ ra thµnh c«ng, gi¸ trÞ =0 lµ thÊt b¹i toµn tËp; =m_nMaxRandom lµ 100% thµnh c«ng
    nDoWaitTime = 3, -- TÝnh b»ng gi©y
    tbItemAllowUpgrade = {
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30228 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30229 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30230 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30231 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30232 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30233 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30234 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30235 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30236 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30237 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30238 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30239 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30240 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30241 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30242 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30243 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30244 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30245 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30246 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30247 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30248 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30249 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30250 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30251 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30252 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30253 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30254 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30255 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30256 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30257 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30258 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30259 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30260 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30261 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30262 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30263 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30264 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30265 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30266 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30267 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30268 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30269 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30270 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30271 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30272 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30273 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30274 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30275 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30276 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30277 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30278 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30279 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30280 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30281 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30282 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30283 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30284 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30285 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30286 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30287 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30288 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30289 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30290 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30291 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 31486 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 31514 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30676 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30677 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30678 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30679 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30680 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30681 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30682 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30683 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30684 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30685 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30686 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30687 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30688 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30689 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30690 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30691 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30692 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30693 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30694 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30695 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30696 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30697 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30698 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30699 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30700 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30701 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30702 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30703 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30704 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30705 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30706 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30707 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30708 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30709 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30710 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30711 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30712 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30713 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30714 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30715 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30716 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30717 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30718 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30719 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30720 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30721 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30722 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30723 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30724 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30725 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30726 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30727 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30728 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30729 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30730 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30731 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30732 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30733 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30734 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30735 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30736 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30737 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30738 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 30739 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 31500 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Bµi", { 0, 102, 31528 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
    tbTargetItem = {
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31132 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31133 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31134 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31135 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31136 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31137 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31138 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31139 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31140 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31141 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31142 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31143 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31144 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31145 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31146 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31147 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31148 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31149 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31150 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31151 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31493 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31521 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31274 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31275 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31276 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31277 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31278 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31279 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31280 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31281 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31282 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31283 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31284 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31285 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31286 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31287 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31288 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31289 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31290 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31291 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31292 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31293 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31507 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Bµi", { 0, 102, 31535 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
});
