WItemUpgrade:RegType({
    nGroupId = 11,
    szLogTitle = "upgrade_thanhlongtuong_uyhotuong_vukhi_100",
    szFeatureName = "N©ng cÊp vò khÝ Thanh Long T­íng thµnh Uy Hæ T­íng 100%", nDateOpen = 1, nDateClose = 1, -- ngµy më tÝnh n¨ng, 1= lu«n më; 0= lu«n ®ãng; ®Þnh d¹ng yyyymmdd tøc lµ ®Þnh ngµy s½n
    szPutinTitle = "§Æt vµo vò khÝ TLT",
    nPutinNum = 1,
    szConsumeInfo = " vµ <color=white>1 vò khÝ Thanh Long T­íng c­êng hãa 15<color>",
    tbMaterialConsume = {
        nBattlePoint = 70000,
        tbItems = {
            { szName = "Thiªn Cang LÖnh", tbProp = { 2, 95, 204 }, nCount = 13 },
            { szName = "Thiªn M«n Kim LÖnh", tbProp = { 2, 1, 30370 }, nCount = 13 },
            { szName = "M¶nh Chu T­íc", tbProp = { 2, 1, 40016 }, nCount = 13 },
            { szName = "Hoµng Kim §¹i Hång Bao", tbProp = { 2, 1, 539 }, nCount = 5 },
        },
    },
    nMatchBodyMode = 4, -- ChÕ ®é tù ®éng tr¶ vÒ vËt phÈm phï hîp víi kiÓu h×nh ng­êi n©ng cÊp, 1= gi÷ nguyªn, 2= auto
    nEnhanceReq = 15, -- Yªu cÇu ®é c­êng hãa tõ mÊy? gi¸ trÞ =0 lµ ko kiÓm tra
    nEnhanceMode = 1, -- ChÕ ®é gi÷ c­êng hãa: gi¸ trÞ =1 lµ gi÷ nguyªn ®é c­êng hãa; =2 lµ trõ ®i 1 ®¬n vÞ; =3 lµ nÕu >= 7 th× vÒ l¹i 7, nÕu < 7 th× vÒ 0; 4= lµ vÒ 0
    nMaxRandom = 10000, -- Random tõ 1 -> m_nMaxRandom
    nLuckyNum = 10000, -- Trong kho¶ng tõ 1 -> m_nLuckyNum sÏ ra thµnh c«ng, gi¸ trÞ =0 lµ thÊt b¹i toµn tËp; =m_nMaxRandom lµ 100% thµnh c«ng
    nDoWaitTime = 3, -- TÝnh b»ng gi©y
    tbItemAllowUpgrade = {
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30804 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Tr­îng (Cao CÊp)", { 0, 8, 30805 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30806 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Ch©m (Cao CÊp)", { 0, 1, 30807 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30808 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n CÇm (Cao CÊp)", { 0, 10, 30809 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30810 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n C«n (Cao CÊp)", { 0, 5, 30811 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30812 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30813 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Th­¬ng (Cao CÊp)", { 0, 6, 30814 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Cung (Cao CÊp)", { 0, 4, 30815 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Song §ao (Cao CÊp)", { 0, 7, 30816 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30817 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30818 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30819 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30820 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30821 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n PhiÕn (Cao CÊp)", { 0, 13, 30822 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Þch (Cao CÊp)", { 0, 12, 30823 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 32201 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30944 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Tr­îng (Cao CÊp)", { 0, 8, 30945 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30946 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Ch©m (Cao CÊp)", { 0, 1, 30947 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30948 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n CÇm (Cao CÊp)", { 0, 10, 30949 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30950 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n C«n (Cao CÊp)", { 0, 5, 30951 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30952 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30953 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Th­¬ng (Cao CÊp)", { 0, 6, 30954 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Cung (Cao CÊp)", { 0, 4, 30955 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Song §ao (Cao CÊp)", { 0, 7, 30956 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30957 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30958 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30959 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30960 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30961 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n PhiÕn (Cao CÊp)", { 0, 13, 30962 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Þch (Cao CÊp)", { 0, 12, 30963 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 32213 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
    tbTargetItem = {
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n §ao (Cao)", { 0, 3, 32263 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Tr­îng (Cao)", { 0, 8, 32264 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Thñ (Cao)", { 0, 0, 32265 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Ch©m (Cao)", { 0, 1, 32266 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n KiÕm (Cao)", { 0, 2, 32267 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n CÇm (Cao)", { 0, 10, 32268 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Thñ (Cao)", { 0, 0, 32269 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n C«n (Cao)", { 0, 5, 32270 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n KiÕm (Cao)", { 0, 2, 32271 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Bót (Cao)", { 0, 9, 32272 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Th­¬ng (Cao)", { 0, 6, 32273 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Cung (Cao)", { 0, 4, 32274 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Song §ao (Cao)", { 0, 7, 32275 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Tr¶o (Cao)", { 0, 11, 32276 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n KiÕm (Cao)", { 0, 2, 32277 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n §ao (Cao)", { 0, 3, 32278 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Bót (Cao)", { 0, 9, 32279 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Tr¶o (Cao)", { 0, 11, 32280 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n PhiÕn (Cao)", { 0, 13, 32281 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n §Þch (Cao)", { 0, 12, 32282 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Chñy (Cao)", { 0, 14, 32283 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n KiÕm (Cao)", { 0, 2, 32284 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu-Uy Hæ T­íng Qu©n §ao (Cao)", { 0, 3, 32395 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Tr­îng (Cao)", { 0, 8, 32396 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Thñ (Cao)", { 0, 0, 32397 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Ch©m (Cao)", { 0, 1, 32398 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n KiÕm (Cao)", { 0, 2, 32399 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n CÇm (Cao)", { 0, 10, 32400 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Thñ (Cao)", { 0, 0, 32401 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n C«n (Cao)", { 0, 5, 32402 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n KiÕm (Cao)", { 0, 2, 32403 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Bót (Cao)", { 0, 9, 32404 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Th­¬ng (Cao)", { 0, 6, 32405 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Cung (Cao)", { 0, 4, 32406 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Song §ao (Cao)", { 0, 7, 32407 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Tr¶o (Cao)", { 0, 11, 32408 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n KiÕm (Cao)", { 0, 2, 32409 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n §ao (Cao)", { 0, 3, 32410 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Bót (Cao)", { 0, 9, 32411 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Tr¶o (Cao)", { 0, 11, 32412 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n PhiÕn (Cao)", { 0, 13, 32413 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n §Þch (Cao)", { 0, 12, 32414 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Chñy (Cao)", { 0, 14, 32415 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n KiÕm (Cao)", { 0, 2, 32416 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
});
