WItemUpgrade:RegType({
    nGroupId = 10,
    szLogTitle = "upgrade_hoaphungtuong_thanhlongtuong_vukhi_100",
    szFeatureName = "N©ng cÊp vò khÝ Háa Phông T­íng thµnh Thanh Long T­íng 100%", nDateOpen = 1, nDateClose = 1, -- ngµy më tÝnh n¨ng, 1= lu«n më; 0= lu«n ®ãng; ®Þnh d¹ng yyyymmdd tøc lµ ®Þnh ngµy s½n
    szPutinTitle = "§Æt vµo vò khÝ HP t­íng",
    nPutinNum = 1,
    szConsumeInfo = " vµ <color=white>1 vò khÝ Háa Phông T­íng c­êng hãa 15<color>",
    tbMaterialConsume = {
        nBattlePoint = 40000,
        tbItems = {
            { szName = "Thiªn Cang LÖnh", tbProp = { 2, 95, 204 }, nCount = 9 },
            { szName = "Thiªn M«n Kim LÖnh", tbProp = { 2, 1, 30370 }, nCount = 9 },
            { szName = "M¶nh Chu T­íc", tbProp = { 2, 1, 40016 }, nCount = 23 },
            { szName = "Hoµng Kim §¹i Hång Bao", tbProp = { 2, 1, 539 }, nCount = 20 },
        },
    },
    nMatchBodyMode = 3, -- ChÕ ®é tù ®éng tr¶ vÒ vËt phÈm phï hîp víi kiÓu h×nh ng­êi n©ng cÊp, 1= gi÷ nguyªn, 2= auto
    nEnhanceReq = 15, -- Yªu cÇu ®é c­êng hãa tõ mÊy? gi¸ trÞ =0 lµ ko kiÓm tra
    nEnhanceMode = 1, -- ChÕ ®é gi÷ c­êng hãa: gi¸ trÞ =1 lµ gi÷ nguyªn ®é c­êng hãa; =2 lµ trõ ®i 1 ®¬n vÞ; =3 lµ nÕu >= 7 th× vÒ l¹i 7, nÕu < 7 th× vÒ 0; 4= lµ vÒ 0
    nMaxRandom = 10000, -- Random tõ 1 -> m_nMaxRandom
    nLuckyNum = 10000, -- Trong kho¶ng tõ 1 -> m_nLuckyNum sÏ ra thµnh c«ng, gi¸ trÞ =0 lµ thÊt b¹i toµn tËp; =m_nMaxRandom lµ 100% thµnh c«ng
    nDoWaitTime = 3, -- TÝnh b»ng gi©y
    tbItemAllowUpgrade = {
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 3, 30432 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 3, 30433 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr­îng (Cao CÊp)", { 0, 8, 30434 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr­îng (Cao CÊp)", { 0, 8, 30435 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Thñ (Cao CÊp)", { 0, 0, 30436 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Thñ (Cao CÊp)", { 0, 0, 30437 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Ch©m (Cao CÊp)", { 0, 1, 30438 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Ch©m (Cao CÊp)", { 0, 1, 30439 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Ch©m (Cao CÊp)", { 0, 1, 30440 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Ch©m (Cao CÊp)", { 0, 1, 30441 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i KiÕm (Cao CÊp)", { 0, 2, 30442 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i KiÕm (Cao CÊp)", { 0, 2, 30443 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i CÇm (Cao CÊp)", { 0, 10, 30444 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i CÇm (Cao CÊp)", { 0, 10, 30445 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Thñ (Cao CÊp)", { 0, 0, 30446 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Thñ (Cao CÊp)", { 0, 0, 30447 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Thñ (Cao CÊp)", { 0, 0, 30448 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Thñ (Cao CÊp)", { 0, 0, 30449 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i C«n (Cao CÊp)", { 0, 5, 30450 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i C«n (Cao CÊp)", { 0, 5, 30451 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i C«n (Cao CÊp)", { 0, 5, 30452 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i C«n (Cao CÊp)", { 0, 5, 30453 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i KiÕm (Cao CÊp)", { 0, 2, 30454 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i KiÕm (Cao CÊp)", { 0, 2, 30455 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i KiÕm (Cao CÊp)", { 0, 2, 30456 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i KiÕm (Cao CÊp)", { 0, 2, 30457 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Bót (Cao CÊp)", { 0, 9, 30458 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Bót (Cao CÊp)", { 0, 9, 30459 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Bót (Cao CÊp)", { 0, 9, 30460 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Bót (Cao CÊp)", { 0, 9, 30461 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Th­¬ng (Cao CÊp)", { 0, 6, 30462 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Th­¬ng (Cao CÊp)", { 0, 6, 30463 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Th­¬ng (Cao CÊp)", { 0, 6, 30464 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Th­¬ng (Cao CÊp)", { 0, 6, 30465 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Cung (Cao CÊp)", { 0, 4, 30466 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Cung (Cao CÊp)", { 0, 4, 30467 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Cung (Cao CÊp)", { 0, 4, 30468 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Cung (Cao CÊp)", { 0, 4, 30469 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 7, 30470 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 7, 30471 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 7, 30472 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 7, 30473 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr¶o (Cao CÊp)", { 0, 11, 30474 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr¶o (Cao CÊp)", { 0, 11, 30475 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr¶o (Cao CÊp)", { 0, 11, 30476 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr¶o (Cao CÊp)", { 0, 11, 30477 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i KiÕm (Cao CÊp)", { 0, 2, 30478 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i KiÕm (Cao CÊp)", { 0, 2, 30479 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 3, 30480 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 3, 30481 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 3, 30482 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §ao (Cao CÊp)", { 0, 3, 30483 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Bót (Cao CÊp)", { 0, 9, 30484 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Bót (Cao CÊp)", { 0, 9, 30485 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Bót (Cao CÊp)", { 0, 9, 30486 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Bót (Cao CÊp)", { 0, 9, 30487 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr¶o (Cao CÊp)", { 0, 11, 30488 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr¶o (Cao CÊp)", { 0, 11, 30489 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr¶o (Cao CÊp)", { 0, 11, 30490 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i Tr¶o (Cao CÊp)", { 0, 11, 30491 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i PhiÕn (Cao CÊp)", { 0, 13, 30492 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i PhiÕn (Cao CÊp)", { 0, 13, 30493 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §Þch (Cao CÊp)", { 0, 12, 30494 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông Nguyªn So¸i §Þch (Cao CÊp)", { 0, 12, 30495 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Háa Phông T­íng Qu©n Chñy (Cao)", { 0, 14, 32167 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 32195 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30536 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30537 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr­îng (Cao CÊp)", { 0, 8, 30538 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr­îng (Cao CÊp)", { 0, 8, 30539 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30540 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30541 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Ch©m (Cao CÊp)", { 0, 1, 30542 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Ch©m (Cao CÊp)", { 0, 1, 30543 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Ch©m (Cao CÊp)", { 0, 1, 30544 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Ch©m (Cao CÊp)", { 0, 1, 30545 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30546 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30547 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n CÇm (Cao CÊp)", { 0, 10, 30548 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n CÇm (Cao CÊp)", { 0, 10, 30549 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30550 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30551 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30552 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30553 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n C«n (Cao CÊp)", { 0, 5, 30554 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n C«n (Cao CÊp)", { 0, 5, 30555 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n C«n (Cao CÊp)", { 0, 5, 30556 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n C«n (Cao CÊp)", { 0, 5, 30557 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30558 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30559 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30560 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30561 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30562 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30563 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30564 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30565 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Th­¬ng (Cao CÊp)", { 0, 6, 30566 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Th­¬ng (Cao CÊp)", { 0, 6, 30567 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Th­¬ng (Cao CÊp)", { 0, 6, 30568 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Th­¬ng (Cao CÊp)", { 0, 6, 30569 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Cung (Cao CÊp)", { 0, 4, 30570 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Cung (Cao CÊp)", { 0, 4, 30571 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Cung (Cao CÊp)", { 0, 4, 30572 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Cung (Cao CÊp)", { 0, 4, 30573 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 7, 30574 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 7, 30575 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 7, 30576 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 7, 30577 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30578 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30579 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30580 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30581 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30582 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30583 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30584 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30585 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30586 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30587 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30588 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30589 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30590 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30591 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30592 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30593 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30594 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30595 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n PhiÕn (Cao CÊp)", { 0, 13, 30596 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n PhiÕn (Cao CÊp)", { 0, 13, 30597 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §Þch (Cao CÊp)", { 0, 12, 30598 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n §Þch (Cao CÊp)", { 0, 12, 30599 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Háa Phông T­íng Qu©n Chñy (Cao)", { 0, 14, 32179 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 32207 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
    tbTargetItem = {
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30804 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Tr­îng (Cao CÊp)", { 0, 8, 30805 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30806 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Ch©m (Cao CÊp)", { 0, 1, 30807 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30808 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n CÇm (Cao CÊp)", { 0, 10, 30809 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30810 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n C«n (Cao CÊp)", { 0, 5, 30811 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30812 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30813 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Th­¬ng (Cao CÊp)", { 0, 6, 30814 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Cung (Cao CÊp)", { 0, 4, 30815 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Song §ao (Cao CÊp)", { 0, 7, 30816 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30817 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30818 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30819 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30820 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30821 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n PhiÕn (Cao CÊp)", { 0, 13, 30822 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Þch (Cao CÊp)", { 0, 12, 30823 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 32201 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30944 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Tr­îng (Cao CÊp)", { 0, 8, 30945 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30946 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Ch©m (Cao CÊp)", { 0, 1, 30947 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30948 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n CÇm (Cao CÊp)", { 0, 10, 30949 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Thñ (Cao CÊp)", { 0, 0, 30950 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n C«n (Cao CÊp)", { 0, 5, 30951 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30952 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30953 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Th­¬ng (Cao CÊp)", { 0, 6, 30954 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Cung (Cao CÊp)", { 0, 4, 30955 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Song §ao (Cao CÊp)", { 0, 7, 30956 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30957 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 30958 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §ao (Cao CÊp)", { 0, 3, 30959 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Bót (Cao CÊp)", { 0, 9, 30960 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Tr¶o (Cao CÊp)", { 0, 11, 30961 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n PhiÕn (Cao CÊp)", { 0, 13, 30962 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Þch (Cao CÊp)", { 0, 12, 30963 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n KiÕm (Cao CÊp)", { 0, 2, 32213 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
});
