WItemUpgrade:RegType({
    nGroupId = 11,
    szLogTitle = "upgrade_thanhlongtuong_uyhotuong_trangsuc3_100",
    szFeatureName = "N©ng cÊp TLT LÖnh Phï thµnh Uy Hæ T­íng Qu©n LÖnh Phï 100%", nDateOpen = 1, nDateClose = 1, -- ngµy më tÝnh n¨ng, 1= lu«n më; 0= lu«n ®ãng; ®Þnh d¹ng yyyymmdd tøc lµ ®Þnh ngµy s½n
    szPutinTitle = "§Æt vµo TLT LÖnh Phï",
    nPutinNum = 1,
    szConsumeInfo = " vµ <color=white>1 Thanh Long T­íng Qu©n LÖnh Phï<color>",
    tbMaterialConsume = {
        nBattlePoint = 70000,
        tbItems = {
            { szName = "Thiªn Cang LÖnh", tbProp = { 2, 95, 204 }, nCount = 14 },
            { szName = "Thiªn M«n Kim LÖnh", tbProp = { 2, 1, 30370 }, nCount = 14 },
            { szName = "M¶nh Chu T­íc", tbProp = { 2, 1, 40016 }, nCount = 31 },
            { szName = "Hoµng Kim §¹i Hång Bao", tbProp = { 2, 1, 539 }, nCount = 15 },
        },
    },
    nMatchBodyMode = 4, -- ChÕ ®é tù ®éng tr¶ vÒ vËt phÈm phï hîp víi kiÓu h×nh ng­êi n©ng cÊp, 1= gi÷ nguyªn, 2= auto
    nEnhanceReq = 0, -- Yªu cÇu ®é c­êng hãa tõ mÊy? gi¸ trÞ =0 lµ ko kiÓm tra
    nEnhanceMode = 1, -- ChÕ ®é gi÷ c­êng hãa: gi¸ trÞ =1 lµ gi÷ nguyªn ®é c­êng hãa; =2 lµ trõ ®i 1 ®¬n vÞ; =3 lµ nÕu >= 7 th× vÒ l¹i 7, nÕu < 7 th× vÒ 0; 4= lµ vÒ 0
    nMaxRandom = 10000, -- Random tõ 1 -> m_nMaxRandom
    nLuckyNum = 10000, -- Trong kho¶ng tõ 1 -> m_nLuckyNum sÏ ra thµnh c«ng, gi¸ trÞ =0 lµ thÊt b¹i toµn tËp; =m_nMaxRandom lµ 100% thµnh c«ng
    nDoWaitTime = 3, -- TÝnh b»ng gi©y
    tbItemAllowUpgrade = {
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31172 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31173 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31174 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31175 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31176 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31177 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31178 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31179 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31180 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31181 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31182 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31183 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31184 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31185 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31186 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31187 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31188 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31189 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31190 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31191 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31495 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31523 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31314 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31315 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31316 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31317 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31318 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31319 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31320 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31321 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31322 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31323 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31324 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31325 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31326 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31327 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31328 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31329 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31330 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31331 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31332 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31333 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31509 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n LÖnh Phï", { 0, 102, 31537 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
    tbTargetItem = {
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31586 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31587 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31588 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31589 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31590 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31591 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31592 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31593 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31594 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31595 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31596 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31597 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31598 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31599 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31600 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31601 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31602 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31603 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31604 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31605 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31606 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31607 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31740 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31741 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31742 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31743 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31744 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31745 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31746 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31747 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31748 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31749 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31750 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31751 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31752 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31753 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31754 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31755 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31756 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31757 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31758 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31759 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31760 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n LÖnh Phï", { 0, 102, 31761 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
});
