WItemUpgrade:RegType({
    nGroupId = 11,
    szLogTitle = "upgrade_thanhlongtuong_uyhotuong_muaoquan_100",
    szFeatureName = "N©ng cÊp mò/¸o/quÇn Thanh Long T­íng thµnh Uy Hæ T­íng 100%", nDateOpen = 1, nDateClose = 1, -- ngµy më tÝnh n¨ng, 1= lu«n më; 0= lu«n ®ãng; ®Þnh d¹ng yyyymmdd tøc lµ ®Þnh ngµy s½n
    szPutinTitle = "§Æt vµo mò/¸o/quÇn TLT",
    nPutinNum = 1,
    szConsumeInfo = " vµ <color=white>1 trang bÞ Thanh Long T­íng (mò/¸o/quÇn) c­êng hãa 15<color>",
    tbMaterialConsume = {
        nBattlePoint = 60000,
        tbItems = {
            { szName = "Thiªn Cang LÖnh", tbProp = { 2, 95, 204 }, nCount = 12 },
            { szName = "Thiªn M«n Kim LÖnh", tbProp = { 2, 1, 30370 }, nCount = 12 },
            { szName = "M¶nh Chu T­íc", tbProp = { 2, 1, 40016 }, nCount = 30 },
            { szName = "Hoµng Kim §¹i Hång Bao", tbProp = { 2, 1, 539 }, nCount = 15 },
        },
    },
    nMatchBodyMode = 4, -- ChÕ ®é tù ®éng tr¶ vÒ vËt phÈm phï hîp víi kiÓu h×nh ng­êi n©ng cÊp, 1= gi÷ nguyªn, 2= auto
    nEnhanceReq = 15, -- Yªu cÇu ®é c­êng hãa tõ mÊy? gi¸ trÞ =0 lµ ko kiÓm tra
    nEnhanceMode = 1, -- ChÕ ®é gi÷ c­êng hãa: gi¸ trÞ =1 lµ gi÷ nguyªn ®é c­êng hãa; =2 lµ trõ ®i 1 ®¬n vÞ; =3 lµ nÕu >= 7 th× vÒ l¹i 7, nÕu < 7 th× vÒ 0; 4= lµ vÒ 0
    nMaxRandom = 10000, -- Random tõ 1 -> m_nMaxRandom
    nLuckyNum = 10000, -- Trong kho¶ng tõ 1 -> m_nLuckyNum sÏ ra thµnh c«ng, gi¸ trÞ =0 lµ thÊt b¹i toµn tËp; =m_nMaxRandom lµ 100% thµnh c«ng
    nDoWaitTime = 3, -- TÝnh b»ng gi©y
    tbItemAllowUpgrade = {
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30570 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30571 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30572 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30573 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30574 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30575 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30576 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30577 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30578 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30579 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30580 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30581 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30582 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30583 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30584 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30585 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30586 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30587 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30588 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30589 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 32157 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 32165 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30611 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30612 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30613 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30614 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30615 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30616 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30617 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30618 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30619 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30620 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30621 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30622 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30623 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30624 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30625 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30626 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30627 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30628 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30629 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30630 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 32159 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 32167 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },

        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30570 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30571 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30572 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30573 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30574 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30575 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30576 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30577 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30578 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30579 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30580 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30581 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30582 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30583 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30584 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30585 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30586 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30587 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30588 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30589 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 32157 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 32165 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30611 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30612 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30613 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30614 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30615 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30616 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30617 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30618 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30619 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30620 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30621 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30622 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30623 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30624 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30625 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30626 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30627 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30628 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30629 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30630 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 32159 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 32167 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },

        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30570 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30571 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30572 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30573 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30574 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30575 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30576 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30577 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30578 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30579 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30580 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30581 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30582 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30583 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30584 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30585 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30586 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30587 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30588 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30589 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 32157 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 32165 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30611 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30612 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30613 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30614 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30615 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30616 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30617 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30618 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30619 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30620 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30621 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30622 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30623 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30624 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30625 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30626 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30627 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30628 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30629 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30630 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 32159 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 32167 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
    tbTargetItem = {
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32171 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32172 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32173 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32174 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32175 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32176 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32177 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32178 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32179 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32180 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32181 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32182 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32183 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32184 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32185 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32186 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32187 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32188 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32189 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32190 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32191 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32192 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32215 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32216 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32217 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32218 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32219 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32220 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32221 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32222 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32223 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32224 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32225 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32226 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32227 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32228 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32229 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32230 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32231 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32232 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32233 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32234 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32235 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Kh«i", { 0, 103, 32236 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },

        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32171 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32172 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32173 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32174 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32175 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32176 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32177 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32178 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32179 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32180 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32181 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32182 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32183 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32184 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32185 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32186 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32187 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32188 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32189 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32190 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32191 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Y", { 0, 100, 32192 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32215 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32216 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32217 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32218 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32219 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32220 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32221 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32222 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32223 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32224 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32225 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32226 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32227 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32228 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32229 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32230 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32231 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32232 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32233 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32234 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32235 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Y", { 0, 100, 32236 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },

        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32171 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32172 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32173 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32174 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32175 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32176 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32177 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32178 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32179 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32180 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32181 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32182 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32183 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32184 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32185 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32186 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32187 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32188 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32189 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32190 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32191 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32192 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32215 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32216 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32217 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32218 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32219 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32220 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32221 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32222 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32223 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32224 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32225 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32226 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32227 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32228 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32229 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32230 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32231 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32232 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32233 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32234 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32235 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu-Uy Hæ T­íng Qu©n Trang", { 0, 101, 32236 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
});
