WItemUpgrade:RegType({
    nGroupId = 9,
    szLogTitle = "upgrade_loihotuong_hoaphungtuong_trangsuc3_100",
    szFeatureName = "N©ng cÊp LHT Phï thµnh Háa Phông T­íng Qu©n LÖnh Phï 100%", nDateOpen = 1, nDateClose = 1, -- ngµy më tÝnh n¨ng, 1= lu«n më; 0= lu«n ®ãng; ®Þnh d¹ng yyyymmdd tøc lµ ®Þnh ngµy s½n
    szPutinTitle = "§Æt vµo LHT Phï",
    nPutinNum = 1,
    szConsumeInfo = " vµ <color=white>1 L«i Hæ T­íng Phï<color>",
    tbMaterialConsume = {
        nBattlePoint = 20000,
        tbItems = {
            { szName = "Thiªn Cang LÖnh", tbProp = { 2, 95, 204 }, nCount = 5 },
            { szName = "Thiªn M«n Kim LÖnh", tbProp = { 2, 1, 30370 }, nCount = 5 },
            { szName = "M¶nh Chu T­íc", tbProp = { 2, 1, 40016 }, nCount = 13 },
            { szName = "Hoµng Kim §¹i Hång Bao", tbProp = { 2, 1, 539 }, nCount = 20 },
        },
    },
    nMatchBodyMode = 3, -- ChÕ ®é tù ®éng tr¶ vÒ vËt phÈm phï hîp víi kiÓu h×nh ng­êi n©ng cÊp, 1= gi÷ nguyªn, 2= auto
    nEnhanceReq = 0, -- Yªu cÇu ®é c­êng hãa tõ mÊy? gi¸ trÞ =0 lµ ko kiÓm tra
    nEnhanceMode = 4, -- ChÕ ®é gi÷ c­êng hãa: gi¸ trÞ =1 lµ gi÷ nguyªn ®é c­êng hãa; =2 lµ trõ ®i 1 ®¬n vÞ; =3 lµ nÕu >= 7 th× vÒ l¹i 7, nÕu < 7 th× vÒ 0; 4= lµ vÒ 0
    nMaxRandom = 10000, -- Random tõ 1 -> m_nMaxRandom
    nLuckyNum = 10000, -- Trong kho¶ng tõ 1 -> m_nLuckyNum sÏ ra thµnh c«ng, gi¸ trÞ =0 lµ thÊt b¹i toµn tËp; =m_nMaxRandom lµ 100% thµnh c«ng
    nDoWaitTime = 3, -- TÝnh b»ng gi©y
    tbItemAllowUpgrade = {
        { [1] = { "Tèng L«i Hæ T­íng Phï", { 0, 102, 30165 } }, nSex = 1, nBody = 1, nRoute = 0, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng L«i Hæ T­íng Phï", { 0, 102, 30166 } }, nSex = 1, nBody = 2, nRoute = 0, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng L«i Hæ T­íng Phï", { 0, 102, 30167 } }, nSex = 2, nBody = 3, nRoute = 0, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng L«i Hæ T­íng Phï", { 0, 102, 30168 } }, nSex = 2, nBody = 4, nRoute = 0, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu L«i Hæ T­íng Phï", { 0, 102, 30201 } }, nSex = 1, nBody = 1, nRoute = 0, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu L«i Hæ T­íng Phï", { 0, 102, 30202 } }, nSex = 1, nBody = 2, nRoute = 0, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu L«i Hæ T­íng Phï", { 0, 102, 30203 } }, nSex = 2, nBody = 3, nRoute = 0, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu L«i Hæ T­íng Phï", { 0, 102, 30204 } }, nSex = 2, nBody = 4, nRoute = 0, nCamp = WEnv.BATTLECAMP_LIEU },
    },
    tbTargetItem = {
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30356 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30357 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30358 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30359 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30360 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30361 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30362 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30363 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30364 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30365 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30366 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30367 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30368 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30369 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30370 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30371 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30372 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30373 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30374 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30375 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30376 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30377 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30378 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30379 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30380 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30381 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30382 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30383 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30384 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30385 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30386 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30387 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30388 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30389 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30390 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30391 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30392 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30393 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30394 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30395 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30396 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30397 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30398 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30399 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30400 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30401 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30402 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30403 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30404 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30405 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30406 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30407 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30408 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30409 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30410 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30411 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30412 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30413 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30414 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30415 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30416 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30417 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30418 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30419 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 31488 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 31516 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30804 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30805 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30806 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30807 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30808 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30809 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30810 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30811 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30812 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30813 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30814 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30815 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30816 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30817 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30818 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30819 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30820 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30821 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30822 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30823 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30824 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30825 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30826 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30827 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30828 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30829 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30830 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30831 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30832 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30833 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30834 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30835 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30836 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30837 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30838 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30839 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30840 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30841 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30842 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30843 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30844 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30845 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30846 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30847 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30848 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30849 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30850 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30851 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30852 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30853 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30854 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30855 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30856 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30857 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30858 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30859 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30860 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30861 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30862 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30863 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30864 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30865 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30866 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 30867 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 31502 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n LÖnh Phï", { 0, 102, 31530 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
});
