WItemUpgrade:RegType({
    nGroupId = 10,
    szLogTitle = "upgrade_hoaphungtuong_thanhlongtuong_muaoquan_100",
    szFeatureName = "N©ng cÊp mò/¸o/quÇn Háa Phông T­íng thµnh Thanh Long T­íng 100%", nDateOpen = 1, nDateClose = 1, -- ngµy më tÝnh n¨ng, 1= lu«n më; 0= lu«n ®ãng; ®Þnh d¹ng yyyymmdd tøc lµ ®Þnh ngµy s½n
    szPutinTitle = "§Æt vµo mò/¸o/quÇn HP t­íng",
    nPutinNum = 1,
    szConsumeInfo = " vµ <color=white>1 trang bÞ Háa Phông T­íng (mò/¸o/quÇn) c­êng hãa 15<color>",
    tbMaterialConsume = {
        nBattlePoint = 40000,
        tbItems = {
            { szName = "Thiªn Cang LÖnh", tbProp = { 2, 95, 204 }, nCount = 8 },
            { szName = "Thiªn M«n Kim LÖnh", tbProp = { 2, 1, 30370 }, nCount = 8 },
            { szName = "M¶nh Chu T­íc", tbProp = { 2, 1, 40016 }, nCount = 22 },
            { szName = "Hoµng Kim §¹i Hång Bao", tbProp = { 2, 1, 539 }, nCount = 15 },
        },
    },
    nMatchBodyMode = 3, -- ChÕ ®é tù ®éng tr¶ vÒ vËt phÈm phï hîp víi kiÓu h×nh ng­êi n©ng cÊp, 1= gi÷ nguyªn, 2= auto
    nEnhanceReq = 15, -- Yªu cÇu ®é c­êng hãa tõ mÊy? gi¸ trÞ =0 lµ ko kiÓm tra
    nEnhanceMode = 1, -- ChÕ ®é gi÷ c­êng hãa: gi¸ trÞ =1 lµ gi÷ nguyªn ®é c­êng hãa; =2 lµ trõ ®i 1 ®¬n vÞ; =3 lµ nÕu >= 7 th× vÒ l¹i 7, nÕu < 7 th× vÒ 0; 4= lµ vÒ 0
    nMaxRandom = 10000, -- Random tõ 1 -> m_nMaxRandom
    nLuckyNum = 10000, -- Trong kho¶ng tõ 1 -> m_nLuckyNum sÏ ra thµnh c«ng, gi¸ trÞ =0 lµ thÊt b¹i toµn tËp; =m_nMaxRandom lµ 100% thµnh c«ng
    nDoWaitTime = 3, -- TÝnh b»ng gi©y
    tbItemAllowUpgrade = {
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30311 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30312 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30313 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30314 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30315 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30316 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30317 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30318 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30319 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30320 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30321 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30322 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30323 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30324 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30325 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30326 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30327 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30328 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30329 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30330 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30331 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30332 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30333 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30334 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30335 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30336 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30337 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30338 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30339 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30340 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30341 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30342 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30343 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30344 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30345 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30346 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30347 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30348 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30349 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30350 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30351 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30352 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30353 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30354 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30355 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30356 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30357 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30358 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30359 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30360 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30361 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30362 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30363 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30364 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30365 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30366 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30367 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30368 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30369 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30370 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30371 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30372 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30373 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30374 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 32153 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 32161 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30439 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30440 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30441 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30442 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30443 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30444 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30445 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30446 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30447 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30448 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30449 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30450 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30451 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30452 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30453 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30454 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30455 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30456 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30457 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30458 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30459 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30460 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30461 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30462 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30463 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30464 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30465 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30466 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30467 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30468 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30469 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30470 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30471 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30472 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30473 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30474 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30475 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30476 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30477 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30478 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30479 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30480 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30481 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30482 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30483 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30484 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30485 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30486 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30487 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30488 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30489 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30490 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30491 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30492 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30493 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30494 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30495 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30496 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30497 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30498 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30499 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30500 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30501 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 30502 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 32155 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Kh«i", { 0, 103, 32163 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },

        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30311 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30312 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30313 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30314 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30315 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30316 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30317 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30318 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30319 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30320 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30321 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30322 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30323 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30324 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30325 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30326 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30327 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30328 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30329 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30330 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30331 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30332 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30333 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30334 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30335 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30336 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30337 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30338 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30339 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30340 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30341 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30342 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30343 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30344 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30345 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30346 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30347 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30348 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30349 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30350 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30351 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30352 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30353 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30354 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30355 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30356 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30357 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30358 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30359 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30360 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30361 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30362 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30363 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30364 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30365 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30366 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30367 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30368 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30369 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30370 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30371 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30372 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30373 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30374 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 32153 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 32161 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30439 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30440 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30441 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30442 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30443 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30444 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30445 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30446 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30447 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30448 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30449 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30450 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30451 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30452 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30453 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30454 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30455 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30456 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30457 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30458 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30459 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30460 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30461 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30462 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30463 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30464 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30465 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30466 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30467 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30468 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30469 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30470 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30471 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30472 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30473 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30474 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30475 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30476 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30477 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30478 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30479 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30480 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30481 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30482 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30483 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30484 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30485 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30486 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30487 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30488 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30489 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30490 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30491 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30492 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30493 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30494 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30495 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30496 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30497 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30498 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30499 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30500 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30501 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 30502 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 32155 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n ChiÕn Bµo", { 0, 100, 32163 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },

        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30311 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30312 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30313 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30314 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30315 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30316 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30317 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30318 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30319 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30320 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30321 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30322 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30323 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30324 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30325 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30326 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30327 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30328 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30329 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30330 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30331 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30332 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30333 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30334 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30335 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30336 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30337 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30338 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30339 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30340 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30341 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30342 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30343 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30344 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30345 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30346 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30347 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30348 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30349 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30350 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30351 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30352 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30353 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30354 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30355 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30356 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30357 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30358 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30359 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30360 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30361 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30362 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30363 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30364 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30365 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30366 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30367 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30368 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30369 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30370 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30371 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30372 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30373 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 30374 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 32153 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Háa Phông T­íng Qu©n Trang", { 0, 101, 32161 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30439 } }, nSex = 1, nBody = 1, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30440 } }, nSex = 1, nBody = 2, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30441 } }, nSex = 1, nBody = 1, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30442 } }, nSex = 1, nBody = 2, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30443 } }, nSex = 1, nBody = 1, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30444 } }, nSex = 1, nBody = 2, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30445 } }, nSex = 1, nBody = 1, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30446 } }, nSex = 1, nBody = 2, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30447 } }, nSex = 2, nBody = 3, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30448 } }, nSex = 2, nBody = 4, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30449 } }, nSex = 2, nBody = 3, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30450 } }, nSex = 2, nBody = 4, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30451 } }, nSex = 2, nBody = 3, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30452 } }, nSex = 2, nBody = 4, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30453 } }, nSex = 1, nBody = 1, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30454 } }, nSex = 1, nBody = 2, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30455 } }, nSex = 2, nBody = 3, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30456 } }, nSex = 2, nBody = 4, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30457 } }, nSex = 1, nBody = 1, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30458 } }, nSex = 1, nBody = 2, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30459 } }, nSex = 2, nBody = 3, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30460 } }, nSex = 2, nBody = 4, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30461 } }, nSex = 1, nBody = 1, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30462 } }, nSex = 1, nBody = 2, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30463 } }, nSex = 2, nBody = 3, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30464 } }, nSex = 2, nBody = 4, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30465 } }, nSex = 1, nBody = 1, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30466 } }, nSex = 1, nBody = 2, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30467 } }, nSex = 2, nBody = 3, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30468 } }, nSex = 2, nBody = 4, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30469 } }, nSex = 1, nBody = 1, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30470 } }, nSex = 1, nBody = 2, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30471 } }, nSex = 2, nBody = 3, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30472 } }, nSex = 2, nBody = 4, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30473 } }, nSex = 1, nBody = 1, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30474 } }, nSex = 1, nBody = 2, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30475 } }, nSex = 2, nBody = 3, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30476 } }, nSex = 2, nBody = 4, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30477 } }, nSex = 1, nBody = 1, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30478 } }, nSex = 1, nBody = 2, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30479 } }, nSex = 2, nBody = 3, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30480 } }, nSex = 2, nBody = 4, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30481 } }, nSex = 1, nBody = 1, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30482 } }, nSex = 1, nBody = 2, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30483 } }, nSex = 2, nBody = 3, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30484 } }, nSex = 2, nBody = 4, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30485 } }, nSex = 1, nBody = 1, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30486 } }, nSex = 1, nBody = 2, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30487 } }, nSex = 1, nBody = 1, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30488 } }, nSex = 1, nBody = 2, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30489 } }, nSex = 2, nBody = 3, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30490 } }, nSex = 2, nBody = 4, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30491 } }, nSex = 1, nBody = 1, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30492 } }, nSex = 1, nBody = 2, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30493 } }, nSex = 2, nBody = 3, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30494 } }, nSex = 2, nBody = 4, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30495 } }, nSex = 1, nBody = 1, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30496 } }, nSex = 1, nBody = 2, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30497 } }, nSex = 2, nBody = 3, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30498 } }, nSex = 2, nBody = 4, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30499 } }, nSex = 2, nBody = 3, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30500 } }, nSex = 2, nBody = 4, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30501 } }, nSex = 2, nBody = 3, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 30502 } }, nSex = 2, nBody = 4, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 32155 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Háa Phông T­íng Qu©n Trang", { 0, 101, 32163 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
    tbTargetItem = {
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30570 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30571 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30572 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30573 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30574 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30575 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30576 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30577 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30578 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30579 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30580 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30581 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30582 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30583 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30584 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30585 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30586 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30587 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30588 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30589 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 32157 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n §Çu", { 0, 103, 32165 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30611 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30612 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30613 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30614 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30615 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30616 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30617 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30618 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30619 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30620 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30621 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30622 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30623 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30624 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30625 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30626 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30627 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30628 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30629 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 30630 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 32159 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n §Çu", { 0, 103, 32167 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },

        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30570 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30571 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30572 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30573 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30574 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30575 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30576 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30577 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30578 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30579 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30580 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30581 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30582 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30583 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30584 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30585 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30586 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30587 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30588 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 30589 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 32157 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n y", { 0, 100, 32165 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30611 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30612 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30613 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30614 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30615 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30616 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30617 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30618 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30619 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30620 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30621 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30622 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30623 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30624 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30625 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30626 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30627 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30628 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30629 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 30630 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 32159 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n y", { 0, 100, 32167 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },

        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30570 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30571 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30572 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30573 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30574 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30575 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30576 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30577 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30578 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30579 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30580 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30581 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30582 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30583 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30584 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30585 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30586 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30587 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30588 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 30589 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 32157 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_TONG },
        { [1] = { "Tèng_Thanh Long T­íng Qu©n Trang", { 0, 101, 32165 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_TONG },

        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30611 } }, nSex = 0, nBody = 0, nRoute = 2, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30612 } }, nSex = 0, nBody = 0, nRoute = 3, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30613 } }, nSex = 0, nBody = 0, nRoute = 4, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30614 } }, nSex = 0, nBody = 0, nRoute = 6, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30615 } }, nSex = 0, nBody = 0, nRoute = 8, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30616 } }, nSex = 0, nBody = 0, nRoute = 9, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30617 } }, nSex = 0, nBody = 0, nRoute = 11, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30618 } }, nSex = 0, nBody = 0, nRoute = 12, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30619 } }, nSex = 0, nBody = 0, nRoute = 14, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30620 } }, nSex = 0, nBody = 0, nRoute = 15, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30621 } }, nSex = 0, nBody = 0, nRoute = 17, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30622 } }, nSex = 0, nBody = 0, nRoute = 18, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30623 } }, nSex = 0, nBody = 0, nRoute = 20, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30624 } }, nSex = 0, nBody = 0, nRoute = 21, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30625 } }, nSex = 0, nBody = 0, nRoute = 23, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30626 } }, nSex = 0, nBody = 0, nRoute = 25, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30627 } }, nSex = 0, nBody = 0, nRoute = 26, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30628 } }, nSex = 0, nBody = 0, nRoute = 27, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30629 } }, nSex = 0, nBody = 0, nRoute = 29, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 30630 } }, nSex = 0, nBody = 0, nRoute = 30, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 32159 } }, nSex = 0, nBody = 0, nRoute = 31, nCamp = WEnv.BATTLECAMP_LIEU },
        { [1] = { "Liªu_Thanh Long T­íng Qu©n Trang", { 0, 101, 32167 } }, nSex = 0, nBody = 0, nRoute = 32, nCamp = WEnv.BATTLECAMP_LIEU },
    },
});
